% Copyright 2018 The MathWorks, Inc.


%% Build the S-function
 cd([p.RootFolder '\CommExample\sfun\']);

mex(['-I' fullfile(p.RootFolder, 'cppzmq')],...
    ['-I' fullfile(p.RootFolder, 'libzmq','include')],...
    ['-L' fullfile(p.RootFolder,'libzmq','bin','x64','Release','v140','dynamic')],...
    '-llibzmq',...
    'sfcn_transmit.cpp',...
    'statcal_util.cpp',...
    'mdlclient.cpp');

mex(['-I' fullfile(p.RootFolder, 'cppzmq')],...
    ['-I' fullfile(p.RootFolder, 'libzmq','include')],...
    ['-L' fullfile(p.RootFolder,'libzmq','bin','x64','Release','v140','dynamic')],...
    '-llibzmq',...
    'sfcn_receive.cpp',...
    'statcal_util.cpp',...
    'mdlclient.cpp');

cd(p.RootFolder)

% At this point, open
